###
POST http://localhost:4000/register
Content-Type: application/json

{
    "username":"hannah",
    "email":"hannah@gmail.com",
    "password":"19942004"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"hannah",
    "password":"19942004"
}


###
GET http://localhost:4000/getuser/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzaGFyb25yYWoiLCJlbWFpbCI6InNoYXJvbmNoZXJhbkBnbWFpbC5jb20iLCJpYXQiOjE3MjcxOTk3NTd9.L3JrPFOSi0N3yNQnjQNAkIbI-UR5z24qMrpszn6yhH8

###

PUT http://localhost:4000/edituser/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJzaGFyb25yYWoiLCJlbWFpbCI6InNoYXJvbmNoZXJhbkBnbWFpbC5jb20iLCJpYXQiOjE3MjcxOTk3NTd9.L3JrPFOSi0N3yNQnjQNAkIbI-UR5z24qMrpszn6yhH8

{
    "username":"sharonraj",
    "email":"sharoncheran@gmail.com",
    "password":"74qa+-*/"
}

###
GET http://localhost:4000/todos/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJoYW5uYWgiLCJlbWFpbCI6Imhhbm5haEBnbWFpbC5jb20iLCJpYXQiOjE3MjcyMDAyODd9.z17SbqnccYWMW2QG8OSYcRLV_T7PzKVqiG0aauv6oy4

###

POST http://localhost:4000/todos
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJoYW5uYWgiLCJlbWFpbCI6Imhhbm5haEBnbWFpbC5jb20iLCJpYXQiOjE3MjcyMDAyODd9.z17SbqnccYWMW2QG8OSYcRLV_T7PzKVqiG0aauv6oy4

{
    "todo": "Plan for Pondichery Trip",
    "description": "Buy some clothes for the trip",
    "status": "pending",
    "priority": "MEDIUM"
}

###

PUT http://localhost:4000/todos/bb5f7b78-0164-4048-a3f9-aef59d34a48a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJoYW5uYWgiLCJlbWFpbCI6Imhhbm5haEBnbWFpbC5jb20iLCJpYXQiOjE3MjcyMDAyODd9.z17SbqnccYWMW2QG8OSYcRLV_T7PzKVqiG0aauv6oy4

{
    "todo": "Study for Your Interview",
    "description": "study Aptitude for half an Hour",
    "priority": "MEDIUM"
}

###

PUT http://localhost:4000/status/bb5f7b78-0164-4048-a3f9-aef59d34a48a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJoYW5uYWgiLCJlbWFpbCI6Imhhbm5haEBnbWFpbC5jb20iLCJpYXQiOjE3MjcyMDAyODd9.z17SbqnccYWMW2QG8OSYcRLV_T7PzKVqiG0aauv6oy4

{
    "status":"in progress"
}

###

DELETE http://localhost:4000/todos/97bc0c11-1e34-4610-81ae-735285b1c9ce
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJoYW5uYWgiLCJlbWFpbCI6Imhhbm5haEBnbWFpbC5jb20iLCJpYXQiOjE3MjcyMDAyODd9.z17SbqnccYWMW2QG8OSYcRLV_T7PzKVqiG0aauv6oy4